print('        __________         ___________')
print('       /          \       /          \ ')
print('      /            \     /            \ ')
print('     /              \   /              \ ')
print('     \               \ /               /')
print('       \                             /')
print('         \        HAAIII QD        /')
print('           \                     /')
print('             \                 /')
print('               \             /')
print('                 \         /')
print('                   \     /')
print('                     \ /')
